sudo: false
language: go

notifications:
  email:
    on_success: change
    on_failure: always

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

env:
  global:
    - GO111MODULE=on
    - GOFLAGS=-mod=vendor

matrix:
  allow_failures:
    - go: master
  fast_finish: true

services:
  - redis-server
before_install:
  - rvm use 2.5 --install --binary --fuzzy
  - gem install anyt
script: make test-ci
