sudo: false
language: go

notifications:
  email:
    on_success: change
    on_failure: always

go:
  - "1.10"
services:
  - redis-server
before_install:
  - rvm use 2.4.2 --install --binary --fuzzy
  - gem install anyt
script: make test-ci
